# Generated by Django 5.0.6 on 2024-06-25 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=100)),
                ('doctor_image', models.ImageField(upload_to='doctor/')),
                ('Department', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=200)),
                ('phoneno', models.BigIntegerField()),
                ('date', models.DateField()),
                ('description', models.TextField(max_length=200)),
                ('doctorinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp1.doctor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp1.userdata')),
            ],
        ),
    ]
